server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service #  lb - load balancer, service discovery
          predicates:
            - Path=/api/auth/**, /api/users/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**, /api/cart/**
        - id: portfolio-service
          uri: lb://portfolio-service
          predicates:
            - Path=/api/portfolio/**
        - id: market-data-service
          uri: lb://market-data-service
          predicates:
            - Path=/api/market-data/**
        - id: ledger-service
          uri: lb://ledger-service
          predicates:
            - Path=/api/ledger/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
        - id: product-service
          uri: lb://product-service
          predicates:
              - Path=/api/products/**, /api/categories/**, /api/brands/**, /api/brand-ticker-mappings/**

      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10    # tokens added per second
            redis-rate-limiter.burstCapacity: 20    # max tokens in bucket
            redis-rate-limiter.requestedTokens: 1   # tokens consumed per request
            key-resolver: "#{@userKeyResolver}"     # SpEL reference to bean

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:8180/realms/equitycart/protocol/openid-connect/certs}

equitycart:
  gateway:
    security:
      open-paths: /api/auth/**, /actuator/**