server:
  port: 8087

equitycart:
  security:
    mode: oauth2

  notification:
    channel: ${NOTIFICATION_CHANNEL:LOG}
    webhook-url: ${NOTIFICATION_WEBHOOK_URL:http://localhost:9999/webhook}
    recipient-email: ${NOTIFICATION_RECIPIENT_EMAIL:demo@equitycart.local}

spring:
  mail:
    host: ${SPRING_MAIL_HOST:localhost}
    port: ${SPRING_MAIL_PORT:1025}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/equitycart_notification}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    # Examples of multiple broker : bootstrap-servers: kafka-1:9092,kafka-2:9092,kafka-3:9092
    consumer:
      group-id: equitycart-notification-group
      auto-offset-reset: earliest # Start from the beginning if no committed offset exists (don't miss events)
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.equitycart.commons.event
